## Numpy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
    
Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists
    
We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions
    
It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**\n",
   
     conda install numpy
    
If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)

In [5]:
#Once you've installed NumPy you can import it as a library

import numpy as np

### NumPy Arrays
 
NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column)
   
Let's begin our introduction by exploring how to create NumPy arrays.
   

In [6]:
my_list = [1,2,3]
my_list   

[1, 2, 3]

In [7]:
#We can create an array by directly converting a list or list of lists
np.array(my_list)

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods
There are lots of built-in ways to generate Arrays

#### arange
Return evenly spaced values within a given interval.

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones
Generate arrays of zeros or ones

In [17]:
np.zeros(3)


array([0., 0., 0.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace
Return evenly spaced numbers over a specified interval.

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye
Creates an identity matrix

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
Numpy also has lots of ways to create random number arrays:

#### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [22]:
np.random.rand(2)

array([0.57162295, 0.34719503])

In [23]:
np.random.rand(5,5)

array([[0.11065339, 0.77757008, 0.23081713, 0.85057756, 0.37944615],
       [0.58254838, 0.29088011, 0.44303272, 0.76981482, 0.59528291],
       [0.85188972, 0.59262418, 0.26975832, 0.63777892, 0.31916997],
       [0.50820375, 0.93227014, 0.67712215, 0.60787309, 0.3243197 ],
       [0.08871598, 0.93999703, 0.94511652, 0.1079799 , 0.48974588]])

#### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [24]:
np.random.randn(2)

array([-0.07150551, -2.27410827])

In [25]:
np.random.randn(5,5)

array([[-1.7616635 , -0.46226311, -0.03067705,  1.0363051 ,  0.73932385],
       [-0.11470445,  0.15706051, -1.26297909, -0.25300292, -0.1221018 ],
       [-0.2931126 ,  0.17836225, -2.38856785, -0.92908912,  1.06090668],
       [-0.4611464 ,  0.14650893, -0.65396761, -1.0593155 , -1.35178633],
       [-0.54793064,  0.59292452, -1.22813876, -1.44272452,  1.09060755]])

#### randint
Return random integers from low (inclusive) to high (exclusive).

In [26]:
np.random.randint(1,100)

73

In [27]:
np.random.randint(1,100,10)

array([50, 21, 24, 18, 46, 17, 42, 97, 85,  5])

### Array Attributes and Methods
Lets discuss some useful attributes and methods or an array:

In [30]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr

array([30,  1, 25, 20, 46, 24, 28, 15, 12, 37])

#### Reshape
Returns an array containing the same data with a new shape.

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [38]:
ranarr

array([30,  1, 25, 20, 46, 24, 28, 15, 12, 37])

In [39]:
ranarr.max()

46

In [40]:
ranarr.min()

1

In [41]:
ranarr.argmin()

1

#### Shape
Shape is an attribute that arrays have (not a method):

In [42]:
# Vector
arr.shape


(25,)

In [43]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [44]:
arr.reshape(1,25).shape

(1, 25)

In [45]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(25,1).shape

(25, 1)

#### dtype
You can also grab the data type of the object in the array:

In [47]:
arr.dtype

dtype('int32')